[BE-15] constraints were changed in liquibase scripts
serkushner/backend-team1 pull request #15
Opened 2021-03-31 23:37 UTC by shpaser2

2021-04-01 05:04 UTC, AlKaliada submitted a review, later dismissed

2021-04-01 05:52 UTC, nazfurdychka submitted a review, later dismissed
please change entities column annotations so that hibernate mapping will correspond liquibase changing scripts

2021-04-01 19:28 UTC, nazfurdychka approved these changes

2021-04-01 19:32 UTC, AlKaliada submitted a review, later dismissed

2021-04-01 21:13 UTC, nazfurdychka submitted a review, later dismissed

2021-04-02 06:21 UTC, serkushner requested changes

2021-04-02 06:21 UTC, serkushner commented on src/main/java/com/exadel/project/internship/entity/Internship.java
> +//    @Column(name = "format")
Pls remove redurant comment

2021-04-02 06:21 UTC, serkushner commented on src/main/resources/db/changelog/changelog-constraints-added.yaml
> +        - onFail: MARK_RAN
Empty precondition?

2021-04-02 06:26 UTC, serkushner requested changes

2021-04-02 06:26 UTC, serkushner commented on src/main/resources/db/changelog/changelog-constraints-added.yaml
> +        - onFail: MARK_RAN
The same

2021-04-02 11:59 UTC, serkushner submitted a review, later dismissed

2021-04-02 12:01 UTC, AlKaliada approved these changes

2021-04-02 12:03 UTC, nazfurdychka approved these changes

2021-04-02 12:06 UTC, merged