1. Add 3 fields to table - country_internship
serkushner/backend-team1 pull request #21
Opened 2021-04-03 06:32 UTC by ValentinKhorunzhyn

2. Add 2 fields to table - internship_subject

2021-04-03 06:38 UTC, AlKaliada approved these changes

2021-04-03 06:49 UTC, serkushner approved these changes

2021-04-03 06:50 UTC, serkushner commented
Maybe, lets have all SQL insert scripts in separate .sql file

2021-04-03 06:51 UTC, serkushner reviewed
Could we move all insert scripts in separate sql files. What do you think?

2021-04-03 06:51 UTC, serkushner requested changes
Maybe, lets have all SQL insert scripts in separate .sql file

2021-04-05 12:13 UTC, serkushner approved these changes

2021-04-05 12:25 UTC, nazfurdychka approved these changes

2021-04-05 12:26 UTC, merged

2021-04-05 12:28 UTC, AlKaliada approved these changes