Be 20 add interviewer entity
serkushner/backend-team1 pull request #26
Opened 2021-04-08 17:56 UTC by ValentinKhorunzhyn

2021-04-12 09:51 UTC, serkushner requested changes

2021-04-12 16:02 UTC, ValentinKhorunzhyn commented on src/main/java/com/exadel/project/internship/controller/InterviewerController.java
> +    public ResponseEntity<List<InterviewerDto>> findAllInterviewers(@RequestParam(value = "search", required = false) String search,
Method renamed

2021-04-12 16:03 UTC, ValentinKhorunzhyn commented on src/main/java/com/exadel/project/internship/service/InterviewerService.java
> +    }
Moved into update method and wrapped by one records

2021-04-12 16:05 UTC, ValentinKhorunzhyn commented on src/test/java/com/exadel/project/controller/InterviewerRestControllerTests.java
> +        dto.setSkype("testSkype");
InterviewerTestData created with two methods which will return HR ore TECH Interviewer

2021-04-12 16:06 UTC, ValentinKhorunzhyn commented on src/test/java/com/exadel/project/controller/InterviewerRestControllerTests.java
> +public class InterviewerRestControllerTests {
Renamed

2021-04-12 16:08 UTC, ValentinKhorunzhyn commented on src/test/java/com/exadel/project/controller/InterviewerRestControllerTests.java
> +        doReturn(dto).when(interviewerService).getById(1L);
InterviewerCrudTest include tests with mock (interviewerRepository)
JsonSerialization TEst and Service tests are deleted.

2021-04-13 13:13 UTC, serkushner approved these changes

2021-04-13 13:28 UTC, nidaffs approved these changes

2021-04-13 13:29 UTC, merged