BE-21-37_interview_entity_and_service_tests_for_service
serkushner/backend-team1 pull request #32
Opened 2021-04-15 08:52 UTC by nazfurdychka

2021-04-15 10:12 UTC, AlKaliada requested changes

2021-04-15 11:17 UTC, nazfurdychka commented on src/main/java/com/exadel/project/interview/entity/Interview.java
> +    @OneToOne(cascade = CascadeType.ALL)
fixed

2021-04-15 11:17 UTC, nazfurdychka commented on src/main/java/com/exadel/project/internship/dto/InternshipDetailsDTO.java
> +    private String additionalInfoInternship;
fixed

2021-04-15 11:17 UTC, nazfurdychka commented on src/main/java/com/exadel/project/interview/entity/InterviewTime.java
> +    @OneToOne(mappedBy = "interviewTime")
fixed

2021-04-15 11:20 UTC, AlKaliada requested changes

2021-04-15 11:20 UTC, AlKaliada commented on src/main/java/com/exadel/project/interview/entity/Interview.java
> +    private InterviewTime interviewTime;
you lost join column

2021-04-15 11:41 UTC, nazfurdychka commented on src/main/java/com/exadel/project/interview/entity/Interview.java
> +    private InterviewTime interviewTime;
thanks, fixed

2021-04-15 12:43 UTC, AlKaliada approved these changes

2021-04-16 09:21 UTC, shpaser2 approved these changes

2021-04-16 09:23 UTC, merged