Be 83 integration tests with docker container
serkushner/backend-team1 pull request #54
Opened 2021-05-14 11:19 UTC by ValentinKhorunzhyn

1. Add Interviewer's integration test with MySQL test container and common test container context
2. Some changes in another tests
3. Unit tests replaced to unit package

2021-05-14 14:24 UTC, serkushner requested changes

2021-05-14 14:24 UTC, serkushner commented on src/main/java/com/exadel/project/administrator/controller/RemoteStorageProviderController.java
>      }
Maybe its better to have username and password in request body?

2021-05-14 14:24 UTC, serkushner commented on src/test/java/com/exadel/project/integration/CommonTestContainerContext.java
> +            );
Pls, lets move such constant in config file

2021-05-15 11:14 UTC, serkushner submitted a review, later dismissed

2021-05-15 11:26 UTC, shpaser2 approved these changes

2021-05-15 12:34 UTC, nazfurdychka approved these changes

2021-05-15 12:49 UTC, merged